### PR TITLE
upgrade node version from 12 to 16

### PR DESCRIPTION
**Pull request by matteoparussini**
#### 📲 What

A description of the change.

#### 🤔 Why
		
Fixing security vulnerabilities
		
#### 🛠 How
		
Upgrade node version

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Comment by matteoparussini** [comment]
Upgrade Node version from 12 to 16

**Comment by ElvenSpellmaker** [comment]
Hey, I think Node 12 is a stacks-wide decision and would need to have an ADR to upgrade this further?

I'm actually unsure as to what this Dockerfile is for as Stacks currently uses github pages for its rendering

**Comment by matteoparussini** [comment]
Ooooo.... ok I didn't know that! Shall I close this PR or shall I let it open? I don't mind to close it, but vulnerabilities will stay there... :)

**Comment by ElvenSpellmaker** [comment]
Leave it here, it's good to open the discussion!

**Pull request closed without merging**
