### PR TITLE
refactor:  update cqrs api documentation - 8266 

### PR DESCRIPTION
**Pull request by AndyHale**
## 📲 What

Updates to the .NET CQRS API documentation from Stacks Cycle 15.

## 🤔 Why
		
Refresh of documentation to ensure that all commands are correct and all options are documented.
		
## 🛠 How
		
Documentation has been adjusted to group relevant infomration and add configuration notes for some of the options, which was missing.

## 👀 Evidence
		
See file changes.
		 
## 🕵️ How to test

Notable changes to consider

*  Removed the domain obejct switcch from Azure Functions commands as it doesn't appear to create the objects.
*  Removed the following switches from the CQRS API as they don't appeart to work: -
    *  -e:fw | --enableFunctionWorker  - Includes the `Azure Function:  CosmosDB Worker` project  in the solution.
    * -e:fl  | --enableFunctionListenee - Includes the `Azure Function:  Service Bus Listener` project in the solution.
    * -e:bw | --enableBackgroundWorker Includes the `Background Worker` project in the solution.

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Review by sharonrussell — APPROVED** [review]

**Review by alexanderwjrussell — APPROVED** [review]
Looks like it should be great! Interested to see how it looks live!

**Comment by AndyHale** [comment]
.azp run

**Pull request merged**
